[tool.poetry]
name = "interval-timer"
version = "0.1.1"
description = ""
authors = ["morefigs <morefigs@gmail.com>"]
readme = "README.md"
packages = [{include = "interval_timer"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
